### ISSUE TITLE
tsf_set_volume below 1

### ISSUE THREAD

**Issue by fucksophie** [schellingb/TinySoundFont#100]
tsf_set_volume instantly mutes itself on values under 1, such as 0.1. Works however with volumes like 2, which is 2x the original volume. Weird.

**Comment by schellingb** [comment]
I just tried it here and it does work, even at 0.01 I can hear it. If you look at the code of the function
```c
TSFDEF void tsf_set_volume(tsf* f, float global_volume)
{
	f->globalGainDB = (global_volume == 1.0f ? 0 : -tsf_gainToDecibels(1.0f / global_volume));
}
```
it doesn't even store the input value as is, instead it calculates a gain that is then applied to all the output. So calling `tsf_set_volume` results in `globalGainDB` being set to -20 which still should be quite audible. Calling it with 2 will result in a gain of +6. Any idea what could be wrong? Do you have any code in between your input and calling the function that perhaps converts it to an integer at some point?

**Comment by fucksophie** [comment]
https://github.com/mppnet/audioengine
No, it goes from int to float.

**Comment by schellingb** [comment]
So there's your issue, this is not a problem with TinySoundFont (this repository), but with that mppned/audioengine (which I have no control over, I've never even heard of it).

Look at this code:

```c
int volume = 100;

...

tsf_set_volume(g_TinySoundFont, volume / 100);
```

So the expression `volume / 100` does an integer division because both sides of the `/` operator are integers. Only after that integer division is the value passed to the function (then as a float), but the integer division has already decided that anything < 100 results in 0. Were either the `volume` variable defined as `float` or the right side of the `/` operator written as `100.0f` it would work out fine, because then the division would be performed as floating point division. You can close this issue here and open one over there about that.

**Comment by fucksophie** [comment]
It's my own repo 🤣, and thanks for spotting the bug and creating such a awesome library. Have you seen the other issue I commented in on this repo?
