### ISSUE TITLE
Midi

### ISSUE THREAD

**Issue by kmatze** [schellingb/TinySoundFont#15]
Hi,
i try to write a wrapper/package for tcl/tk in c. I created a function 
      "play soundfont midifile" 
(similar tu exemple3.c) but i dont know how to split the different functions in seperate c functions.

My Goal is to seperate These steps in tcl commands
- initialize the audio System
- load soundfont
- load midi file
- play (in Background)
- pause, resume and stop
- get actual information
- load new midi file and soundfont (and re-initialized the audiosystem?)
- shutdown the System.

The other think is how can i read the playing Information (whole length, actual Position etc.)?  

thx a lot - kmatze

**Comment by schellingb** [comment]
Hi there

TinySoundFont and TinyMidiLoader are kept separate, so the application using them needs to handle playback timing. So how you handle playing, stopping and the current playback position is up to you.
In example3 the play position is kept in a simple global variable g_Msec which automatically increases as audio is playing, and never stops.

What audio system do you plan to use? Is there some tcl/tk audio system available? The rest all depends a little bit how that audio system lets you feed audio data.

You can get some information about the loaded MIDI file with tml_get_info. Most relevant is time_length which is the length of the song in milliseconds.
```c
tml_message *TinyMidiLoader = tml_load(...);
unsigned int MidiLengthMsec;
tml_get_info(TinyMidiLoader, NULL, NULL, NULL, NULL, &MidiLengthMsec);
```

When you want to play a new MIDI file you need to reset the synthesizer like this:
```c
for (int i = 0; i < 16; i++) 
{
	tsf_channel_note_off_all(g_TinySoundFont, i);
	tsf_channel_set_preset(g_TinySoundFont, i, 0);
	tsf_channel_set_pitchwheel(g_TinySoundFont, i, 8192);
	tsf_channel_set_pan(g_TinySoundFont, i, .5f);
	tsf_channel_set_volume(g_TinySoundFont, i, 1.f);
}
```
Maybe this should go into a function, now that I think about it (-:

You can load a new soundfont by closing the current one and loading a new instance. If you want to continue playing a MIDI file you need to set all the channel settings (bank/preset, pitchwheel, pan, volume) to what it was on the old instance.

**Comment by kmatze** [comment]
thx for your answer, but i cannot understand all Things :-(
I try to describe my Problems:

Working System is win10, tcltk 8.4 (old but tiny!), gcc 4.8.3

These are my functions, defined in c (as tcl package):
	init
	loadSF2 [soundfont]
	loadMID [midifile]
	play
	pause  (toogle command to pause and continue)
	stop
	info
	shutdown

Problems i have with play, stop and loadMID (not the first time but beginnend with the second time)
steps i do:

1) init  - goes
2) loadSF2 - goes
3) loadMID - goes
4) play - goes
5) pause (halt) - goes
    paus (coninue) - goes
6) info (all info from tml_get_info and g_Msec) - goes
7) stop - how to?
    i use SDL_PauseAudio(1), i think it is not the right way
8) loadSF2 (a new soundfont) - goes
9) loadMID (a new midifile) - goes
    but the the g_Msec will goes away, not stopped
10) play - how to Position to the start of the new midifile?
    only a short noise and g_Msec goes away
11) shutdown - works

i Show you the whole c file in the atached file.

thx for your Passion and greetings - kmatze
-----------------------------------------------------------------------------------------------------------------
[matzsf.txt](https://github.com/schellingb/TinySoundFont/files/1803780/matzsf.txt)

**Comment by schellingb** [comment]
Hi again

I noticed your code is never resetting g_Msec to zero after stopping. So I think you can just add `g_Msec = 0;` just before `SDL_PauseAudio(0);` inside the function `Play_cmd`. Because play only plays from stopped state so that seems reasonable. Would this fix most of your issues?

Calling `SDL_PauseAudio(1);` inside the function `Stop_cmd` is fine I think. Your stsPlayer controls the play state and you have checks for it in the Pause_cmd and Play_cmd so that's OK.

If you ever want additional features like playing multiple MIDI files at the same time or playing other sound sources (like sound effects if you want to make a game) you probably will run into additional problems but for a simple MIDI player this should work.  
If you need that you are probably advised to step away from my hacked together "minisdl_audio" and go with some proper SDL and SDL-mixer bindings for your language, seems like http://sqlitestudio.pl/tclmixer/ has that (mind you I know next to nothing about tcl/tk).

Good luck!

**Comment by kmatze** [comment]
hi,
thx for your helpfull support. Now, it works fine. I have upload my work on github:
https://github.com/kmatze/matzsf
greetings - kmatze
