### ISSUE TITLE
Feature request: Fix whatever is breaking this sf/midi combo?

### ISSUE THREAD

**Issue by kavika13** [schellingb/TinySoundFont#16]
I'm sorry, this request is fairly vague :| It is sort of testing the limit of my sf/midi knowledge and debugging skills!

Playback is much better with most soundfonts w/ your previous 5 or 6 commits (🎈), but now I'm trying to find a *small* soundfont I can legally distribute w/ an open source game I'm porting.

I'm having a problem with this combo:
- SoundFont: GeneralUser GS v1.471.sf2 (http://schristiancollins.com/generaluser.php) (same problem with the older "softsynth friendly" version)
- This midi file: [LEVEL1.zip](https://github.com/schellingb/TinySoundFont/files/1844087/LEVEL1.zip)
- The example3 midi player

Other soundfonts are working fine w/ this track in the example3 player, and this sound font is working fine with this track in a different bassmidi-based player.

The problem is on track 12, when using Lead 6 Voice (85). The track has long held notes, modulation, and aftertouch. The result of playback in example3 is like someone trying to do rapid notes on an instrument with a very long attack, so it barely plays or doesn't sound at all.

I'd just use a different working soundfont, since other ones are working just fine with your lib, but they're either too big, or of dubious legality. I am working on a FOSS game port, so I'd rather not try anything on-the-sly!

**Comment by schellingb** [comment]
Hi there!

Thanks for the great test case, it was indeed a problem with the SoundFont parsing.  
`GeneralUser GS v1.471.sf2` uses global zones in both presets and instruments with multiple instrument layers which makes it quite a good test font.
TSF actually basically ignored the global zone in presets only handling them on the instrument level, so that was a rather big oversight. It's now fixed since commit 1bfb361.

Glad you didn't just resort to using another soundfont and opened this issue :-)

**Comment by kavika13** [comment]
Tried it with the new sound font. The fix sounds good to me!
