### ISSUE TITLE
SFZ not working in SFZero

### ISSUE THREAD

**Issue by jamiebullock** [schellingb/TinySoundFont#3]
Hi,

This is actually a report against your fork of SFZero, but there's no issue tracker currently for that repo so I'm posting here.

SF2 works fine in your SFZero, however SFZ just produces silence (or at least some very low level noise). 

I will look into this myself, but I'm asking here in case you're aware of anything obvious that may be causing the problem

The original stevefolta SFZ works fine, so this is definitely a regression.

**Comment by schellingb** [comment]
Hi there!

Thank you for testing my fork with SFZ files which I frankly have to admit I never did myself. 

Turns out the non-SF2 based regions had an uninitialized lowpass filter which basically just generated noise. I just committed a change that initializes the filter as non-active for SFZ file voices.

By the way, my fork only loads settings for the modulation envelope, modulation LFO and vibrato LFO from SF2 files. You'd need to add opcodes for SFZ files in SFZReader::read along the SF2 changes my initial commit did. Check the diff here: https://github.com/schellingb/SFZero/commit/811212a5937c9496c5b8c5d31254621adebfe93f#diff-fac7a9479e83322c065cc94417b08dd1

Hopefully you can try again with the newest revision. My test didn't result in silence it actually generated really loud noise, which was fixed by the latest change. Hopefully yours is fixed as well :-)

Thanks again,
\ Bernhard

**Comment by jamiebullock** [comment]
Hi Bernhard,

Thanks for the quick fix. I can confirm this is working.

I've also made a few minor fixes and submitted a PR for them.

Another thing that could be done is update the jucer file to JUCE 5. Currently it doesn't work due to the change in module name from `juce_audio_processor` to `juce_audio_processors`

Happy to submit a PR for that

**Comment by jamiebullock** [comment]
Hi again @schellingb 

Just looking at integrating the LFO stuff for SFZ.

Can you help me with the architecture a bit? I don't really understand the semantics of `modLfoToX`

It looks like there are 2 LFO per voice: `modlfo` and `viblfo`. When we say `region->modLfoToPitch = ` what is the rvalue there? It feels like a boolean that toggles the assignment of the modlfo to pitch. If so, some questions:

- does this mean that we share a single LFO for pitch, filter and amplifier?
- why not three separate LFOs for these?

If I can understand it a bit better, I can submit a PR to add LFO support for SFZ.

Cheers,

Jamie

**Comment by schellingb** [comment]
The members in SFZRegion are named directly after the generators as they are defined in the SF2 spec.
You can find the spec here: http://freepats.zenvoid.org/sf2/sfspec24.pdf
The generators are defined in '8.1.2 Generator Enumerators Defined' and the LFOs are outlined in '9.1.6 Low Frequency Oscillators'.
It explains that there is one modulation LFO (pitch, filter, amplitude) and one vibrato LFO (pitch only). I don't think there is a stated reason, maybe it was deemed well enough and a good balance performance-wise for an implementation in 1996.

I still have a hard time to find a good spec of SFZ opcodes. There is a list here: http://www.sfzformat.com/index.php?title=LFO
The wiki is quite incomplete, but it hints to how the system does not seem to be straight-forward to be ported from an SF2 implementation. SFZ 1 is maybe similar? Full support for assignable LFOs (SFZ 2) would be quite a task I think.

**Comment by jamiebullock** [comment]
Ah, OK. Thank you so much for this quick and helpful feedback.

I need to think about what to do here. The main difficulty I see here is using a common DSP core for both SFZ and SF2. Since my primary concern is SFZ it might make more sense for me to just focus on that and not worry too much about maintaining a kind of lowest common denominator compatibility layer with SF2. It's clear even from this basic LFO stuff that as soon as you deviate from basic things like sample playback and looping the specs are quite different.

Also, my ecosystem is quite heavily based around JUCE which has a growing DSP library, so for my purposes it makes sense to take advantage of that. However, I will try to contribute back what I can.
