### ISSUE TITLE
Missing sample in every buffer window

### ISSUE THREAD

**Issue by martin-minovski** [schellingb/TinySoundFont#4]
I tried with different soundfont libraries, as well as on different platforms (BeagleBone+Bela, Windows 10 + standard soundcard [examples/example2.c]), but there is a persistent clicking noise - its frequency is correlated with the buffer length. Recorded the output, here's how it looks like:

[https://pasteboard.co/GM3rN13.png](https://pasteboard.co/GM3rN13.png)

Looks almost as if there is one missing sample for each buffer window i.e. tsf_render_float and tsf_render_short producing less samples than defined in the the function argument? Any ideas whether it's something obvious?

Thanks!

**Comment by schellingb** [comment]
Hi there,
Thank you for your report and testing.

I carefully stepped through the voice rendering code requesting various sample counts and I ended up finding a different issue where the state of the lowpass filter was not carried across multiple render calls. But that ended up only introducing some noise, never skipped a sample or outputted zero like your recording seems to contain.

Did you run example2.c as is or was your code just based on it? If you modified it, can you post code?

Also, instead of recording a playback you could dump the rendered buffers directly into a file and then inspect it with the tool Audacity with File -> Import -> Raw Data.

Something kinda like this:
```c++
enum { BUFFER_WINDOW = 333 };
float Buf[BUFFER_WINDOW * 2];
FILE* f = fopen("D:\\dev\\github\\TinySoundFont\\tsf_work\\out.raw", "wb");
tsf* TSF = tsf_load_filename("D:\\dev\\github\\TinySoundFont\\trunk\\examples\\florestan-subset.sf2");
tsf_set_output(TSF, TSF_STEREO_INTERLEAVED, 44100, 0);
tsf_note_on(TSF, 0, 48, 1.0f);
for (int i = 0; i < 5; i++)
{
	tsf_render_float(TSF, Buf, BUFFER_WINDOW, 0);
	fwrite(Buf, sizeof(Buf), 1, f);
}
tsf_close(TSF);
fclose(f);
```

Hopefully we can figure this one out (-:
\ Bernhard

**Comment by martin-minovski** [comment]
It was more than 1 sample per render portion, also seemingly more than zero, but still distorted - and indeed it was the lowpass filter causing this; your latest commit produced a beautiful piano sound (with the help of the right soundfont)! Thanks! #nicelib

**Comment by schellingb** [comment]
Awesome to hear! Super stoked we found that one!
Thanks again for reporting.
