### ISSUE TITLE
Set panning for each note_on

### ISSUE THREAD

**Issue by martin-minovski** [schellingb/TinySoundFont#8]
Hi there! Would it be possible to assign panning factor for each individual note (voice)? I noticed you're setting some panning values for each voice in the note_on function, but I don't want to break anything there ;)

Great piece of lib, keep it up!

Cheers

Martin

**Comment by kode54** [comment]
Panning is something ordinarily controlled by a midi controller, and usually applies to all notes on a given channel.

**Comment by schellingb** [comment]
@kode54 TinySoundFont contains only the synth part it doesn't deal in MIDI channels. Because multiple MIDI channels could work on the same preset, it actually would be quite hard to correctly implement a MIDI controller around it in its current state.
I guess an option to pass in a channel number for note_on's with further manipulations of all playing voices having a certain channel would be great to have.

**Comment by frabert** [comment]
Would it be possibile to instead have panning values for presets? So that we can have better control over the mixing of the various presets played by a single TSF instance

**Comment by martin-minovski** [comment]
@frabert You should be able to do this by setting a preset to a TSF channel using:
`tsf_channel_set_bank_preset(tsf* f, int channel, int bank, int preset_number);`
After that you call `tsf_channel_note_on` and setting the panning of that channel will affect all playing notes :)
Closing this as #10 has implemented the request.
